SELECT *
FROM BRIGHT.BRIGHT_COFFEE.BRIGHT_COFFEE_TABLE;
-------------
---I want to check my categorical columns
SELECT DISTINCT STORE_LOCATION
FROM BRIGHT.BRIGHT_COFFEE.BRIGHT_COFFEE_TABLE;
-------------
SELECT DISTINCT PRODUCT_CATEGORY
FROM BRIGHT.BRIGHT_COFFEE.BRIGHT_COFFEE_TABLE;
-------------
---GET THE DATE WHEN SHOP WAS OPENED
SELECT MIN(TRANSACTION_DATE)AS SHOP_OPENING_DATE
FROM BRIGHT.BRIGHT_COFFEE.BRIGHT_COFFEE_TABLE;

--GET THE DATE SHOP WAS CLOSED
SELECT MAX(TRANSACTION_DATE)AS LAST_OPERATING_DATE
FROM BRIGHT.BRIGHT_COFFEE.BRIGHT_COFFEE_TABLE;
------
SELECT TRANSACTION_DATE,
DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
CASE 
WHEN DAY_NAME IN ('Sun','Sat')then 'Weekend'
Else 'Weekday'
End as DAY_CLASSIFICATION,
MONTHNAME(TRANSACTION_DATE)AS MONTH_NAME,
TRANSACTION_TIME,
CASE
WHEN TRANSACTION_TIME BETWEEN '06:00:00'AND '11:59:59'THEN 'MORNING'
WHEN TRANSACTION_TIME BETWEEN '12:00:00'AND '16:59:59'THEN 'AFTERNOON'
WHEN TRANSACTION_TIME BETWEEN '17:00:00'AND '20:59:59'THEN 'EVENING'
END AS TIME_CLASSIFICATION,
HOUR(TRANSACTION_TIME)AS HOUR_OF_DAY,
store_location,
product_category,
product_detail,
product_type,
unit_price,
transaction_qty,
COUNT(DISTINCT TRANSACTION_ID)AS NUMBER_SALES,
SUM(transaction_qty*unit_price) AS Revenue
FROM BRIGHT.BRIGHT_COFFEE.BRIGHT_COFFEE_TABLE
GROUP BY ALL;


 
